# -*- coding: utf-8 -*-
"""Act-CORRELACION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KbijwngkzhpuJc08VbZ0IMxWlq-IIZ2J
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Act-CORRELACION").getOrCreate()

spark

csv_file_path = "/content/Libro 3(Sheet1).csv"
variable = spark.read.csv(csv_file_path, header = True, inferSchema=True)

variable.show()

correlacion = variable.select(corr(col("Publicidad"),col("Ventas")).alias("correlacion")).collect()[0]["correlacion"]

print("La correlacion es: ", correlacion)