# -*- coding: utf-8 -*-
"""Act-MEDIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17b_zcmunr1XpMeDpS9cWfdqzk79rnUJ1
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark = SparkSession.builder.appName("Act-MEDIA").getOrCreate()

spark

"""
Contexto:
El estudiante quiere saber el promedio que obtuvo en el ciclo
"""

csv_file_path = "/Libro(Sheet1).csv"
variable = spark.read.csv(csv_file_path, header = True, inferSchema=True)

variable.show()

promedio = variable.select(mean(col("Calificacion")).alias("La media o el promedio del ciclo del estudiante"))

promedio.show()